### ISSUE TITLE
Plots not rendering following R update

### ISSUE THREAD

**Issue by sciencebuff** [ropensci/plotly#1042]
Plotly is not rendering in shiny following updating from R 3.3.2 to R 3.4.0. I have tried different combinations of versions. Below is an example that gives no plot output in the shiny browser (but does when only the plot_ly call is made).

```r
require(shiny)
require(plotly)

ui <- fluidPage(
  plotlyOutput("plot")
)

server <- function(input, output) {
  output$plot <- renderPlotly({
    plot_ly(mtcars, x = ~mpg, y = ~wt)
  })
}

shinyApp(ui, server)
```

> R version 3.4.0 (2017-04-21)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.4

> Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

> locale:
[1] C

> attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

> other attached packages:
[1] plotly_4.7.0.9000  ggplot2_2.2.1.9000 shiny_1.0.3.9000  

> loaded via a namespace (and not attached):
 [1] Rcpp_0.12.11      magrittr_1.5      munsell_0.4.3     viridisLite_0.2.0 colorspace_1.3-2  xtable_1.8-2      R6_2.2.1          rlang_0.1.1      
 [9] httr_1.2.1        plyr_1.8.4        dplyr_0.5.0       tools_3.4.0       grid_3.4.0        data.table_1.10.4 gtable_0.2.0      DBI_0.6-1        
[17] htmltools_0.3.6   lazyeval_0.2.0    digest_0.6.12     assertthat_0.2.0  tibble_1.3.3      tidyr_0.6.3       purrr_0.2.2.2     htmlwidgets_0.9  
[25] mime_0.5          compiler_3.4.0    scales_0.4.1      jsonlite_1.5      httpuv_1.3.3

**Comment by bastiwasti** [comment]
Same issue as reported in the other thread https://github.com/ropensci/plotly/issues/1037

**Comment by cpsievert** [comment]
Thanks for letting me know. Should be fixed now. Try re-installing `devtools::install_github('ropensci/plotly')`

**Comment by iron0012** [comment]
Hi, I am still not able to produce Plotly graphics in Shiny. I ran devtools::install_github('ropensci/plotly') within the last 20 minutes, but it has not helped. 

For instance, upon running the example at the bottom of this page https://plot.ly/r/shiny-tutorial/
a window with the message "Hover on a point!" is produced, but the actual Plotly plot is not displayed.

Thanks again for your help with this set of issues, I'm excited about the new features in the most recent version of Plotly for R.

**Comment by cpsievert** [comment]
Sorry about that, it should work now.
