### ISSUE TITLE
Colors missing out from plot when assigning colors to data with NA's

### ISSUE THREAD

**Issue by filipwastberg** [ropensci/plotly#1126]
So I'm building a shiny app for data on all polls made in Sweden from 1998-2017. 

The data can be accessed here:
```{r}
get_polls <- function(){
  # Get URL
  x <- RCurl::getURL("https://raw.githubusercontent.com/MansMeg/SwedishPolls/master/Data/Polls.csv")
  
  # Read csv
  df <- utils::read.csv(textConnection(x), stringsAsFactors = FALSE)
  df$PublYearMonth <- as.Date(paste("01", df$PublYearMonth, sep = " "), format="%d%Y-%b")
  df$Company <- factor(df$Company)
  df$PublDate <- lubridate::ymd(df$PublDate)
  df$collectPeriodFrom <- lubridate::ymd(df$collectPeriodFrom)
  df$collectPeriodTo <- lubridate::ymd(df$collectPeriodTo)
  df$house <- factor(df$house)
  dplyr::as_data_frame(df)
}
library(dplyr)
library(tidyr)
polls <- get_polls() %>%
  select(PublYearMonth, M:FI, house) %>%
  gather("parti", value = procent, -PublYearMonth, -house)
```

Each party has an official colour that needs to be consistent for different inputs
So I create a data frame with party colors in order to join with data

```{r}
partycolors <- data.frame(parti = levels(as.factor(polls$parti)) ,
                          color = as.factor(c("#009933", "#CD1B68", "#000077",
                                              "#006AB3", "#52BDEC", "#83CF39",
                                              "#E8112d", "#DDDD00", "#DA291C")))

# Join data
polls <- full_join(polls, partycolors, by = c("parti"))
```

When I plot the data the last party, FI, gets the color of SD. 

```{r}
library(plotly)
polls %>%
  filter(house == "Demoskop") %>%
  plot_ly(x = ~PublYearMonth,
          y = ~procent,
          text = ~paste('Party:', parti,
                        '<br>Percent:', procent,
                        '<br>Date:', PublYearMonth),
          hoverinfo = 'text',
          mode = "markers",
          marker = list(color = ~color))
```

However, when I filter out NA's (both SD and FI are reletively new parties) and plot it again the colors are correct
```{r}
polls <- polls %>%
  filter(!is.na(procent))

# Plot data
polls %>%
  filter(house == "Demoskop") %>%
  plot_ly(x = ~PublYearMonth,
          y = ~procent,
          text = ~paste('Party:', parti,
                        '<br>Percent:', procent,
                        '<br>Date:', PublYearMonth),
          hoverinfo = 'text',
          mode = "markers",
          marker = list(color = ~color))
```

Any ideas why?

```
R version 3.4.1 RC (2017-06-22 r72857)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=Swedish_Sweden.1252  LC_CTYPE=Swedish_Sweden.1252    LC_MONETARY=Swedish_Sweden.1252 LC_NUMERIC=C                   
[5] LC_TIME=Swedish_Sweden.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] plotly_4.7.1       ggplot2_2.2.1.9000 bindrcpp_0.2       dplyr_0.7.2        tidyr_0.7.1       

loaded via a namespace (and not attached):
 [1] RColorBrewer_1.1-2 digest_0.6.12      htmltools_0.3.6    R6_2.2.2           scales_0.4.1       assertthat_0.2.0   grid_3.4.1        
 [8] bitops_1.0-6       stringr_1.2.0      knitr_1.17         httr_1.3.1         tidyselect_0.1.1   munsell_0.4.3      compiler_3.4.1    
[15] tibble_1.3.4       httpuv_1.3.5       crosstalk_1.0.0    mime_0.5           pkgconfig_2.0.1    viridisLite_0.2.0  lubridate_1.6.0   
[22] shiny_1.0.5        purrr_0.2.3        jsonlite_1.5       plyr_1.8.4         glue_1.1.1         data.table_1.10.4  stringi_1.1.5     
[29] magrittr_1.5       gtable_0.2.0       rlang_0.1.2        colorspace_1.3-2   yaml_2.1.14        RCurl_1.95-4.8     tools_3.4.1       
[36] bindr_0.1          htmlwidgets_0.9    xtable_1.8-2       lazyeval_0.2.0     Rcpp_0.12.12    
```

**Comment by cpsievert** [comment]
I think this issue is fixed now?

**Comment by yioryos-nardis** [comment]
I still get this problem with the colors though. I opened an issue today about it: https://github.com/plotly/dashR/issues/143
What do you think the issue is here?
