### ISSUE TITLE
'scatter' objects don't have these attributes: 'stackgroup'

### ISSUE THREAD

**Issue by cristofertadrissi** [ropensci/plotly#1359]
Hi all,

just contacting you because I am having some problems regarding with the generation of one plot and looking for some help, I am trying to plot one stacked area chart with cumulative values using plot_ly but I am getting this error al the time:

'scatter' objects don't have these attributes: 'stackgroup', 'groupnorm'
Valid attributes include:
'type', 'visible', 'showlegend', 'legendgroup', 'opacity', 'name', 'uid', 'ids', 'customdata', 'selectedpoints', 'hoverinfo', 'hoverlabel', 'stream', 'transforms', 'x', 'x0', 'dx', 'y', 'y0', 'dy', 'text', 'hovertext', 'mode', 'hoveron', 'line', 'connectgaps', 'cliponaxis', 'fill', 'fillcolor', 'marker', 'selected', 'unselected', 'textposition', 'textfont', 'r', 't', 'error_x', 'error_y', 'xcalendar', 'ycalendar', 'xaxis', 'yaxis', 'idssrc', 'customdatasrc', 'hoverinfosrc', 'xsrc', 'ysrc', 'textsrc', 'hovertextsrc', 'textpositionsrc', 'rsrc', 'tsrc', 'key', 'set', 'frame', 'transforms', '_isNestedKey', '_isSimpleKey', '_isGraticule', '_bbox'
 

I have been following the instructions to build this graph showed in this link: https://plot.ly/r/filled-area-plots/
Also I if run the code  of the section stacked area chart with cumulative values in a Rstudio session I get the same problem.

Code that works on the website

```r
library(plotly)

data <- t(USPersonalExpenditure)
data <- data.frame("year"=rownames(data), data)

p <- plot_ly(data, x = ~year, y = ~Food.and.Tobacco, name = 'Food and Tobacco', type = 'scatter', mode = 'none', stackgroup = 'one', groupnorm = 'percent', fillcolor = '#F5FF8D') %>%
  add_trace(y = ~Household.Operation, name = 'Household Operation', fillcolor = '#50CB86') %>%
  add_trace(y = ~Medical.and.Health, name = 'Medical and Health', fillcolor = '#4C74C9') %>%
  add_trace(y = ~Personal.Care, name = 'Personal Care', fillcolor = '#700961') %>%
  add_trace(y = ~Private.Education, name = 'Private Education', fillcolor = '#312F44') %>%
  layout(title = 'United States Personal Expenditures by Categories',
         xaxis = list(title = "",
                      showgrid = FALSE),
         yaxis = list(title = "Proportion from the Total Expenditures",
                      showgrid = FALSE,
                      ticksuffix = '%'))
```

Also it appears on the reference of scatter objects  that "stackgroup" key is available
https://plot.ly/r/reference/

So, maybe there is something that I am missing.....

Kind Regards

**Comment by cpsievert** [comment]
These are newly released plotly.js attributes -- #1338 will fix it.

**Comment by cristofertadrissi** [comment]
Hello, if I just execute the following code, should be working?

plotlyMainBundle <- function() {
  htmltools::htmlDependency(
    "plotly-main", 
    version = "1.40.1",
    version = "1.41.0",
    src = depPath("plotlyjs"),
    script = "plotly-latest.min.js",
    all_files = FALSE
   )
 }
 
Thanks.

**Comment by ethanyxu** [comment]
@cristofertadrissi I had the exactly the same issue. Installing the dev version of plotly worked for me:

`devtools::install_github("ropensci/plotly")`

**Comment by dean-n** [comment]
I see #1338 has been merged, but I still get the following when I try to run the example in the first post:

`Warning messages:
1: 'scatter' objects don't have these attributes: 'stackgroup'
Valid attributes include:
'type', 'visible', 'showlegend', 'legendgroup', 'opacity', 'name', 'uid', 'ids', 'customdata', 'selectedpoints', 'hoverinfo', 'hoverlabel', 'stream', 'transforms', 'x', 'x0', 'dx', 'y', 'y0', 'dy', 'text', 'hovertext', 'mode', 'hoveron', 'line', 'connectgaps', 'cliponaxis', 'fill', 'fillcolor', 'marker', 'selected', 'unselected', 'textposition', 'textfont', 'r', 't', 'error_x', 'error_y', 'xcalendar', 'ycalendar', 'xaxis', 'yaxis', 'idssrc', 'customdatasrc', 'hoverinfosrc', 'xsrc', 'ysrc', 'textsrc', 'hovertextsrc', 'textpositionsrc', 'rsrc', 'tsrc', 'key', 'set', 'frame', 'transforms', '_isNestedKey', '_isSimpleKey', '_isGraticule', '_bbox'`

**Comment by juliendiot42** [comment]
@cpsievert do you have any idea of when the package will be updated on the CRAN ?
Thank-you ! :)
