### ISSUE TITLE
interaction between ggplotly & flexboard's tabset 

### ISSUE THREAD

**Issue by wibeasley** [ropensci/plotly#1652]
A corner case was identified by in https://stackoverflow.com/questions/58739271/plots-not-showing-in-flexdashboard-tabs (not my post).  I use plotly & flexdashboard a lot, so I thought I'd help narrow down the conditions in which things fail.

The failure to plot is caused by some three-way interaction.  It passes if any one of these isn't present. 
1. plotly's `ggplotly()` translating a valid ggplot object.
1. ggplot's `fill` set to the same aesthetic as `y`.  (Being set to the same as `x` doesn't cause the problem.)
1. flexdashboard's `.tabset` class being set (and it's on the 2nd tab).

*Inconsistent Workaround*: sometimes it works if you use a duplicate variable for `fill` (assuming it happens to be the same as `y`.)  See `y2` in the code above.  But not always; defining `da$ns2 <- rep(1:2,6)` in the SO post does *not* fix it (dropping the `fill` aesthetic does work).

````rmd
---
title: "Tabset Column"
output: 
  flexdashboard::flex_dashboard
---

Column {.tabset}
-------------------------------------
    
### Chart 1

### Chart 2

There should be a bar graph below.

```{r}
library(ggplot2)

d <-data.frame(x=letters[1:12], y=1:12, y2=1:12)
p <- ggplot(d) + geom_bar(aes(x=x, y=y, fill=y), stat="identity") # Fails w/ ggplotly
# p <- ggplot(d) + geom_bar(aes(x=x, y=y, fill=x), stat="identity") # Works w/ ggplotly
# p <- ggplot(d) + geom_bar(aes(x=x, y=y, fill=y2), stat="identity") # Works w/ ggplotly

plotly::ggplotly(p)
# p # Always works.
```   
````

### Fails w/ `fill=y` & w/ `Column {.tabset}`
![image](https://user-images.githubusercontent.com/1372890/68413103-27ced080-0153-11ea-8d76-bf6e5f4661e0.png)

### Passes with*out* `ggplotly()` & w/ `fill=y` &  w/ `Column {.tabset}`
![image](https://user-images.githubusercontent.com/1372890/68413819-a0825c80-0154-11ea-99f4-e89264486c69.png)

### Passes w/ `fill=x` & w/ `Column {.tabset}`
![image](https://user-images.githubusercontent.com/1372890/68413150-459c3580-0153-11ea-8bdb-7884a475590c.png)

### Passes w/ `fill=y` & w/ `Column` (ie, no `{.tabset}`)
![image](https://user-images.githubusercontent.com/1372890/68413358-b3e0f800-0153-11ea-8b88-21edb973af8d.png)

**Comment by cpsievert** [comment]
This issue should be fixed now in the dev version -- `remotes::install_github("ropensci/plotly")`

Also, a CRAN release will be coming by the end of next week

**Comment by wibeasley** [comment]
@cpsievert, the example above still doesn't show the bar graph, unless `{.tabset}` is deleted.  I'm using the most recent version of flexdashboard and plotly.  Am I doing something wrong?

```
flexdashboard   0.5.1.9000 2020-02-13 [1] Github (rstudio/flexdashboard@404cdac)
plotly          4.9.2      2020-02-13 [1] Github (ropensci/plotly@a63b048)  
```

![image](https://user-images.githubusercontent.com/1372890/74460334-57782d80-4e52-11ea-8a23-a41987d5eff7.png)

**Comment by cpsievert** [comment]
In your original example, there is no plot that is supposed to appear in the first tab, but it appears in the 2nd tab, right? If I'm missing something, please provide another reprex.

**Comment by daszlosek** [comment]
For those still having this problem with `plotly_4.9.2.1`  and `flexdashboard_0.5.2`.  `remotes::install_github("ropensci/plotly")` seems to work.
