### ISSUE TITLE
`ERROR: dependency ‘viridis’ is not available for package ‘plotly’`

### ISSUE THREAD

**Issue by chriddyp** [ropensci/plotly#247]
hey @cpsievert  - not sure about the best practices for dependencies, but is it possible to include `viridis` as a requirement that gets automatically installed? seems like folks have to `install.packages('viridis’)` before the install `plotly`

**Comment by cpsievert** [comment]
Ah, it's [listed under IMPORTS](https://github.com/ropensci/plotly/blob/5cdd985a0d5eb1479cf972fc1712c4125025f8e2/DESCRIPTION#L33), but it must not install by default since it didn't appear in the NAMESPACE as well. https://github.com/ropensci/plotly/commit/ce587aa0a2fc6ddc9c4abfab7283ea1666ff3df8 should fix it

**Comment by chriddyp** [comment]
I'm still getting this issue with a fresh install

**Comment by cpsievert** [comment]
Is the problem with installing viridis, or the problem reported in #253?

**Comment by 13bzhang** [comment]
I have been getting this error message when trying to install `viridis` by `install.packages("viridis")`. I can install it fine via GitHub. But the package is on CRAN, so...

```r
Warning in install.packages :
  package ‘viridis’ is not available (as a binary package for R version 3.1.3)
```
I have R version 3.1.3 on my OS X.

**Comment by chriddyp** [comment]
The problem being that the library isn't installed automatically as a dependency:

```
> devtools::install_github("ropensci/plotly")
Downloading github repo ropensci/plotly@master
Installing plotly
Skipping 1 packages not available: viridis
Installing 11 packages: colorspace, dichromat, ggplot2, gtable, labeling, munsell, plyr, proto, RColorBrewer, reshape2, scales
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore CMD INSTALL  \
  '/private/var/folders/d4/c4jpnb754pj3cfj5pv8y9m080000gn/T/Rtmp5ZPPeo/devtools5dcc767c747/ropensci-plotly-a97299c'  \
  --library='/Library/Frameworks/R.framework/Versions/3.1/Resources/library'  \
  --install-tests 

ERROR: dependency ‘viridis’ is not available for package ‘plotly’
* removing ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/plotly’
Error: Command failed (1)
```

**Comment by 13bzhang** [comment]
I upgraded to R 3.2.1. Got the following error message when I first tried to re-install `plotly`:

```r
ERROR: dependency ‘viridis’ is not available for package ‘plotly’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/plotly’
```
I was able to `install.packages("viridis")` and then successfully install `plotly` from GitHub.

**Comment by chriddyp** [comment]
It looks like for 3.1.3 `install.packages("viridis", type="source")` is the way to go. Not sure how this option can get added into the imports in `DESCRIPTION`

**Comment by sjmgarnier** [comment]
@chriddyp It must be a problem with 3.1.3. On 3.2.1, installing plotly automatically installs viridis from source (at least on my setup).

**Comment by cpsievert** [comment]
I think the real problem is that a binary for OS X Mavericks currently isn't available -> https://cran.r-project.org/web/packages/viridis/

@sjmgarnier it'd be very much appreciated if you could contact CRAN and ask why it isn't available!

**Comment by sjmgarnier** [comment]
@cpsievert I believe the answer is here: https://cran.r-project.org/web/checks/check_results_viridis.html. It seems that the minimum versions of stats and grDevices required in the DESCRIPTION file of viridis are not available for Mavericks.

**Comment by cpsievert** [comment]
Ah, bummer. At least for the time being, we can recommend Mac OS X users to install plotly's dependencies from source:

```r
devtools::install_github("ropensci/plotly", type = "source")
```

@chriddyp next week I can look into moving viridis to SUGGESTS instead of IMPORTS so that installation isn't required if you think that's worth doing

**Comment by 13bzhang** [comment]
Hi guys, I accidentally merged something to master when I was pulling. Can you please revert it back? I am really sorry.

**Comment by cpsievert** [comment]
@sjmgarnier is it necessary to [depend on 3.2.1 and higher for stats/grDevices?](https://github.com/sjmgarnier/viridis/blob/2c4dadc3af5016d449caf1e654bcff91a17e9b09/DESCRIPTION#L21) If not, it'd be a huge help to us if you could relax that restriction and resubmit to CRAN!

**Comment by sjmgarnier** [comment]
@cpsievert Probably not. It was just the version of R that I used to develop the package originally. Can you submit a PR for the DESCRIPTION file with what would work for you? The repo is at https://github.com/sjmgarnier/viridis. Also the repo version has scales function for ggplot2 and I meant to submit the new version to CRAN this week or next anyway.

**Comment by sjmgarnier** [comment]
@cpsievert FYI, I submitted to CRAN the updated version of the viridis package. It should be up on CRAN very soon. Sorry it took so long.

**Comment by sjmgarnier** [comment]
@cpsievert On CRAN now: https://cran.r-project.org/web/packages/viridis/. It should solve the dependency problem. Sorry it took me so long.

**Comment by cpsievert** [comment]
@sjmgarnier thanks!

**Comment by chriddyp** [comment]
A user wrote in this morning who is still seeing the issue on OSX 10.10.3:

Mac OS X 10.10.3 (14D131)
RStudio
Version 0.98.1091
R version 3.1.2 (2014-10-31) -- "Pumpkin Helmet"
```
> devtools::install_github("ropensci/plotly")
Downloading github repo ropensci/plotly@master
Installing plotly
Skipping 1 packages not available: viridis
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore CMD INSTALL '/private/var/folders/7d/rg798mld7y99607lpwvrx86x0810l1/T/RtmptBiPiT/devtools170a30ba3c64/ropensci-plotly-2a043c0' --library='/Users/dfernandez/Library/R/3.1/library'  \
  --install-tests 

ERROR: dependency ‘viridis’ is not available for package ‘plotly’
* removing ‘/Users/dfernandez/Library/R/3.1/library/plotly’
Error: Command failed (1)
```

**Comment by sjmgarnier** [comment]
@chriddyp viridis CRAN page shows the binaries available for Snow Leopard and Mavericks: https://cran.r-project.org/web/packages/viridis/

**Comment by sjmgarnier** [comment]
@chriddyp devtools::install_github("ropensci/plotly") worked without a hitch on my OS X 10.10.5. It found and installed viridis without any problem.

**Comment by chriddyp** [comment]
Got it - yeah, it looks like an issue with 3.1.2

**Comment by cpsievert** [comment]
@chriddyp did you recommend trying this?

```r
devtools::install_github("ropensci/plotly", type = "source")
```

**Comment by cpsievert** [comment]
Actually it's probably better to recommend doing this:

```r
install.packages("viridis", type = "source")
devtools::install_github("ropensci/plotly")
```

**Comment by chabir** [comment]
Any recommendation for ?
"ERROR: dependency 'jsonlite' is not available for package 'plotly'
* removing 'C:/Users/Owner/Documents/R/win-library/3.2/plotly'
Error: Command failed (1)"

version.string R version 3.2.1 (2015-06-18)

**Comment by chriddyp** [comment]
hey @chabir - moving to a new issue to make that issue more discoverable: https://github.com/ropensci/plotly/issues/282

**Comment by weilu** [comment]
`install.packages("viridis", type = "source")` didn't do it for me. I had to `devtools::install_github("sjmgarnier/viridis")`
