### ISSUE TITLE
Allow for discrete color scales with fewer than three colors

### ISSUE THREAD

**Issue by RoyalTS** [ropensci/plotly#670]
This slight variation on an [example from the docs](https://plot.ly/r/user-guide/#sequential-color-mappings) throws a warning:

    > plot_ly(iris, x = Petal.Length, y = Petal.Width,
              color = Sepal.Length>6, colors = c("#132B43", "#56B1F7"),
              mode = "markers")

    Warning message:
    In RColorBrewer::brewer.pal(N, "Set2") :
      minimal value for n is 3, returning requested palette with 3 different levels

I [asked about this on SO](http://stackoverflow.com/questions/38740837/custom-discrete-color-scale-in-plotly/38744227) and the issue seems to be that `build_plotly()` shouldn't be calling `brewer.pal()` if the data has fewer than three classes

**Comment by cpsievert** [comment]
This is now fixed:

```r
plot_ly(iris, x = ~Petal.Length, y = ~Petal.Width,
          color = ~Sepal.Length>6, colors = c("#132B43", "#56B1F7"))
```

**Comment by wkumler** [comment]
Sorry to dredge up old threads, but I'm still seeing this warning in 2020. If we *don't* specify a manual scale for colors, the warning still appears:

```r
plot_ly(iris, x = ~Petal.Length, y = ~Petal.Width, color = ~Sepal.Length>6)
```

The code causing this error is part of a Shiny app where I don't know in advance how many colors there will be, so I can't assign a manual scale. When the user supplies data for only only one or two traces, this warning is thrown.

**Comment by wrathematics** [comment]
We have an R package using plotly that produces lots of these RColorBrewer warnings. Our fix was to drop this into a file `R/warnings.r`

```r
apply_with_warn_filter <- function(throwing_fun, warn_filter, ...) {
  warnwrap <- function(w) {
    if (grepl(pattern = warn_filter, x = w$message)) {
      invokeRestart("muffleWarning")
    } else {
      w
    }
  }

  withCallingHandlers(throwing_fun(...), warning = warnwrap)
}

#' @importFrom knitr knit_print
knit_print.api_plot <- function(...) {
  apply_with_warn_filter(
    throwing_fun = plotly::knit_print.api_plot,
    warn_filter = "returning requested palette with 3 different levels",
    ...
  )
}

registerS3method("knit_print", "plotly", knit_print.api_plot)
```
