### ISSUE TITLE
plotly no longer display properly in Rstudio viewer

### ISSUE THREAD

**Issue by happyshows** [ropensci/plotly#717]
Hi,

I observed this after upgrading to 4.3.7 I believe...

![image](https://cloud.githubusercontent.com/assets/3208181/18549672/7993b8c6-7b15-11e6-840e-e01058730b96.png)

```
R version 3.3.0 (2016-05-03)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] plotly_4.4.2  ggplot2_2.1.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.6          magrittr_1.5         devtools_1.11.1.9000 munsell_0.4.3        colorspace_1.2-6    
 [6] xtable_1.8-2         viridisLite_0.1.3    R6_2.1.3             httr_1.2.1           plyr_1.8.4          
[11] dplyr_0.5.0          tools_3.3.0          grid_3.3.0           gtable_0.2.0         DBI_0.5             
[16] git2r_0.15.0         withr_1.0.1          htmltools_0.3.5      yaml_2.1.13          lazyeval_0.2.0      
[21] assertthat_0.1       digest_0.6.10        tibble_1.2           shiny_0.13.2.9005    tidyr_0.6.0         
[26] base64enc_0.1-3      htmlwidgets_0.7      curl_0.9.7           memoise_1.0.0        mime_0.5            
[31] scales_0.4.0         jsonlite_1.0         httpuv_1.3.3        
```

**Comment by cpsievert** [comment]
Can you tell me what you see when you "right-click" ->"Inpsect Element" -> "Console"?

Does it render in any other browsers?

What version of RStudio? Try upgrading?

**Comment by cpsievert** [comment]
Also, just curious, do these examples render for you?

```r
plot_ly()
plot_ly(x = 1:10, y = 1:10)
d <- diamonds[sample(nrow(diamonds), 1000), ]
plot_ly(d, x = ~carat, y = ~price, text = ~paste("Clarity: ", clarity),
        mode = "markers", color = ~carat, size = ~carat, marker = list(line = list(color = "black")))
```

**Comment by happyshows** [comment]
Hi Carson,

below is the image for diamond dataset
![image](https://cloud.githubusercontent.com/assets/3208181/18556667/ae7dcfc4-7b31-11e6-8bbb-f6ee15197448.png)

I am using the  0.99.1208 (preview) version of Rstudio, Viewer was working fine until recently. If I call 'external browser' in Viewer, I do see plotly in my chrome.

I tried the  plot_ly(x = 1:10, y = 1:10)  and it works fine.
![image](https://cloud.githubusercontent.com/assets/3208181/18556755/fb3d7c56-7b31-11e6-870a-2490510d41ab.png)

**Comment by cpsievert** [comment]
Thanks @happyshows! And this example doesn't work either?

```r
d <- diamonds[sample(nrow(diamonds), 1000), ]
plot_ly(d, x = ~carat, y = ~price, text = ~paste("Clarity: ", clarity),
        mode = "markers", color = ~carat, size = ~carat, marker = list(line = list(color = "black")))
```

**Comment by happyshows** [comment]
No it didn't work...

![image](https://cloud.githubusercontent.com/assets/3208181/18557149/64c53b18-7b33-11e6-9fbd-cc128af74150.png)
![image](https://cloud.githubusercontent.com/assets/3208181/18557160/6dce244a-7b33-11e6-9ff8-aae5f4b369b0.png)

**Comment by cpsievert** [comment]
Ok, thanks. It looks like recent versions of [plotly.js (v1.17.0 and up) are making use of `ArrayBuffer`](https://github.com/plotly/plotly.js/pull/869), which isn't defined in older versions of RStudio. 

Not sure which version of RStudio introduced `ArrayBuffer`, but I can confirm it exists in the current stable release of RStudio (0.99.903), so I'd recommend upgrading if you can...

**Comment by happyshows** [comment]
I have submitted a ticket to rstudio and request for comment/fix.

**Comment by kdorman42** [comment]
For anyone else here looking for answers -- Reinstalling the latest of RStudio didn't work. I did a fresh install of R and cleared my default browser in Windows 10, and that fixed the issue.

**Comment by cpsievert** [comment]
The dev version of plotly should fix the issue -- `devtools::install_github("ropensci/plotly")`

**Comment by dayaefrail** [comment]
I am seeing this issue as well;  I am running R version 3.3.3 and RStudio version 1.1.350 with plotly version 4.7.1. Reinstalling both R and RStudio did not help. I've uploaded screenshot of the error here: [stackoverflow](https://stackoverflow.com/questions/45992809)
I'm able to see the plot once I launch it in a browser (default: Chrome) though. Any suggestions on how this could be resolved?

**Comment by dayaefrail** [comment]
I tried reinstalling R and RStudio, cleared my default browser, and downloaded the dev version of plotly, but I'm still having issues. I'll comment again if I find a fix.

**Comment by DaveRGP** [comment]
Me as well

**Comment by cpsievert** [comment]
If you're still having problems, please follow my directions here https://github.com/ropensci/plotly/issues/717#issuecomment-247333997, and report back (in another issue preferably if the errors look different)

**Comment by roelhogervorst** [comment]
newest version of rstudio dailies does this too. 

When I right click and inspect element - console on the zoom window: the console is empty
when I right click the viewer window in rstudio and inspect-console I see errormessages:

```
3loading-background.png Failed to load resource: the server responded with a status of 404 (Not Found)
rstudio-0.js:5627 5: Error occurred while executing method
2: [system] No such file or directory
2loading-background.png Failed to load resource: the server responded with a status of 404 (Not Found)
rstudio-0.js:5627 5: Error occurred while executing method
2: [system] No such file or directory
rstudio-0.js:5627 6: (TypeError) : Cannot read property 'b' of null

loading-background.png Failed to load resource: the server responded with a status of 404 (Not Found)
rstudio-0.js:5627 5: Error occurred while executing method
2: [system] No such file or directory
:23377/events/get_events Failed to load resource: net::ERR_EMPTY_RESPONSE
:23377/rpc/ping Failed to load resource: net::ERR_EMPTY_RESPONSE
rstudio-0.js:5627 6: Unable to establish connection with R session

:23377/rstudio/deferredjs/53C832444D00140118C7663A901C2378/26.cache.js Failed to load resource: net::ERR_EMPTY_RESPONSE
:23377/rpc/set_client_state Failed to load resource: net::ERR_EMPTY_RESPONSE
:23377/rpc/get_environment_state Failed to load resource: net::ERR_CONNECTION_REFUSED
:23377/events/get_events Failed to load resource: net::ERR_CONNECTION_REFUSED
:23377/rstudio/deferredjs/53C832444D00140118C7663A901C2378/26.cache.js?autoRetry=1 
```

I am using RStudio Version 1.2.1049
with plotly 4.8.0.9000 (just downloaded the newest version)
on a macbook pro 2015 high sierra.

**Comment by hafez-ahmad** [comment]
R version 4.0.0
d <- diamonds[sample(nrow(diamonds), 1000), ]
plot_ly(d, x = ~carat, y = ~price, text = ~paste("Clarity: ", clarity),
+         mode = "markers", color = ~carat, size = ~carat, marker = list(line = list(color = "black")))
No trace type specified:
  Based on info supplied, a 'scatter' trace seems appropriate.
  Read more about this trace type -> https://plot.ly/r/reference/#scatter
Warning message:
`line.width` does not currently support multiple values.
