### ISSUE TITLE
Panning with shapes crash R Studio

### ISSUE THREAD

**Issue by rhelmus** [ropensci/plotly#839]
Hello,

The following example from [the shapes examples](https://plot.ly/r/shapes/) will result in a crash of R studio when panning and ran in the viewer (default) or internal browser:

```R
library(plotly)
p <- plot_ly(economics, x = ~date, y = ~uempmed, name = "unemployment")

# add shapes to the layout
p <- layout(p, title = 'Highlighting with Rectangles',
             shapes = list(
               list(type = "rect",
                    fillcolor = "blue", line = list(color = "blue"), opacity = 0.3,
                    x0 = "1980-01-01", x1 = "1985-01-01", xref = "x",
                    y0 = 4, y1 = 12.5, yref = "y"),
               list(type = "rect",
                 fillcolor = "blue", line = list(color = "blue"), opacity = 0.2,
                 x0 = "2000-01-01", x1 = "2005-01-01", xref = "x",
                 y0 = 4, y1 = 12.5, yref = "y")))
```

Using different shapes result in the same crash. In Chrome it does not crash. I'm using the last R studio. 

```R
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=Dutch_Netherlands.1252  LC_CTYPE=Dutch_Netherlands.1252    LC_MONETARY=Dutch_Netherlands.1252
[4] LC_NUMERIC=C                       LC_TIME=Dutch_Netherlands.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] plotly_4.5.6.9000 ggplot2_2.2.1    

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.8            RColorBrewer_1.1-2     colourpicker_0.3       plyr_1.8.4             base64enc_0.1-3       
 [6] ProtGenerics_1.6.0     tools_3.3.2            digest_0.6.10          viridisLite_0.1.3      jsonlite_1.2          
[11] tibble_1.2             gtable_0.2.0           lattice_0.20-34        Matrix_1.2-7.1         shiny_0.14.2          
[16] DBI_0.5-1              parallel_3.3.2         httr_1.2.1             dplyr_0.5.0            S4Vectors_0.12.1      
[21] htmlwidgets_0.8        stats4_3.3.2           multtest_2.30.0        grid_3.3.2             Biobase_2.34.0        
[26] R6_2.2.0               survival_2.40-1        BiocParallel_1.8.1     RANN_2.5               tidyr_0.6.0           
[31] purrr_0.2.2            magrittr_1.5           mzR_2.8.0              scales_0.4.1           codetools_0.2-15      
[36] htmltools_0.3.5        MASS_7.3-45            splines_3.3.2          xcms_1.50.0            BiocGenerics_0.20.0   
[41] MassSpecWavelet_1.40.0 assertthat_0.1         mime_0.5               colorspace_1.3-2       xtable_1.8-2          
[46] httpuv_1.3.3           miniUI_0.1.1           lazyeval_0.2.0         munsell_0.4.3          Cairo_1.5-9```


Regards,
Rick

**Comment by cpsievert** [comment]
Hmm, I suspect this was a plotly.js issue that may have been fixed recently...try using the latest dev (GitHub) version?

**Comment by rhelmus** [comment]
Thanks for the response. Just updated to the last git version and it still happens, unfortunately.

**Comment by mrska** [comment]
Has this problem been fixed? I'm using plotly 4.7.1 and I'm having exactly the same problem.
