### ISSUE TITLE
issue: position_dodge alters hover values

### ISSUE THREAD

**Issue by rubenalv** [ropensci/plotly#986]
Problem: using `position_dodge` in at least `geom_point` seems to incorrectly assign the *group* values shown when hovering on a point. This is related to whether or not the values in the plot x-axis factor are alphabetically ordered.

Example:
```r
library(ggplot2)
library(plotly)

#Data with x-axis factor in alphabetical order (a, b, c):
data <- data.frame('Col1' = c('a', 'b', 'c'), 'Col2'= factor(1:3), Col3 = c('A1', 'A2', 'A3'), 'Val' = c(10,5,1))
#Hovering on plot dots gives correct values, regardless of position_dodge.
ggplotly(ggplot(data, aes(x = Col1, y = Val, group = Col2:Col3)) + geom_point())
ggplotly(ggplot(data, aes(x = Col1, y = Val, group = Col2:Col3)) + geom_point(position = position_dodge(0.6)))

#Data with x-axis factor in non alphabetical order (c, a, b):
data1 <- data.frame('Col1' = c('c', 'a', 'b'), 'Col2'= factor(1:3), Col3 = c('A1', 'A2', 'A3'), 'Val' = c(10,5,1))
#Hovering on plot dots gives correct values if no position_dodge is used:
ggplotly(ggplot(data1, aes(x = Col1, y = Val, group = Col2:Col3)) + geom_point())
#Hovering on plot dots gives incorrect values (as if the x-axis levels had been reordered?) if position_dodge is used:
ggplotly(ggplot(data1, aes(x = Col1, y = Val, group = Col2:Col3)) + geom_point(position = position_dodge(0.6)))
```
Both solution and temporary workaround are appreciated. Plotly is superb, thank you so much for putting your time on it.

**Comment by cpsievert** [comment]
I can't seem to replicate the problem. Are you using the latest version? This might have been fixed recently.

If not, please be a bit more specific with what exactly went wrong.

**Comment by rubenalv** [comment]
Hello @cpsievert ,

I have added my sessionInfo() at the bottom, and tried and install the dev version of ggplot2, but the issue persist.
To be more specific, try:
```r
library(ggplot2)
library(plotly)
data <- data.frame('Col1' = c('a', 'b', 'c'), 'Col2'= factor(1:3), Col3 = c('A1', 'A2', 'A3'), 'Val' = c(10,5,1))
data1 <- data.frame('Col1' = c('c', 'a', 'b'), 'Col2'= factor(1:3), Col3 = c('A1', 'A2', 'A3'), 'Val' = c(10,5,1))

ggplotly(ggplot(data1, aes(x = Col1, y = Val, group = Col2:Col3:as.factor(Val))) + geom_point(position = position_dodge(0.6)))
```
When I hover on coordinate `a:5`, I get this:

| | | |
|  -----  |  -----  |  -----  |
|  *Col1:*   |  a  |  (correct)  |
|  *Val:*  |  5  |  (correct)  |
|  *Col2:Col3:as.factor(Val):*  |  1:A1:10  |  (incorrect, it should be 2:A2:5 as shown below)  |

`data1` real values for coordinate `a:5` are:

|Col1 | Col2 | Col3 | Val|
|-----|-----|-----|-----|
| a | 2 | A2 | 5|

This does not happen if you do not use position_dodge, or if Col1 values are alphabetically ordered, as in `data`.

Hope this helps better.




sessionInfo():

R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

Matrix products: default
BLAS: /usr/lib/atlas-base/atlas/libblas.so.3.0
LAPACK: /usr/lib/atlas-base/atlas/liblapack.so.3.0

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8     LC_MONETARY=en_GB.UTF-8   
 [6] LC_MESSAGES=en_GB.UTF-8    LC_PAPER=en_GB.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] plotly_4.6.0         ggplot2_2.2.1.9000   BiocInstaller_1.26.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.10      knitr_1.15.1      magrittr_1.5      devtools_1.12.0   munsell_0.4.3     xtable_1.8-2      colorspace_1.3-2 
 [8] viridisLite_0.2.0 R6_2.2.0          httr_1.2.1        plyr_1.8.4        dplyr_0.5.0       tools_3.4.0       grid_3.4.0       
[15] gtable_0.2.0      DBI_0.6-1         git2r_0.18.0      withr_1.0.2       htmltools_0.3.6   crosstalk_1.0.0   yaml_2.1.14      
[22] lazyeval_0.2.0    assertthat_0.2.0  digest_0.6.12     tibble_1.3.0      shiny_1.0.3       purrr_0.2.2       tidyr_0.6.1      
[29] htmlwidgets_0.8   curl_2.6          memoise_1.1.0     mime_0.5          labeling_0.3      compiler_3.4.0    scales_0.4.1     
[36] jsonlite_1.4      httpuv_1.3.3
